config/routes.rb
Rails.application.routes.draw do

  resources :to_dos

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/to_do.rb
class ToDo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/to_dos_controller.rb
class ToDosController < ApplicationController

  def index
    @todos = ToDo.all
  end

  def show
    @todo = ToDo.find(params[:id])
  end

  def new
    @todo = ToDo.new
  end

  def create
    todo = ToDo.new(todos_params)
    if todo.save
      redirect_to to_dos_path
    else
      render :new
    end
  end

  def update
    @todo = ToDo.find(params[:id])
    if @todo.update(todos_params)
      redirect_to to_do_path(@todo)
    else
      render :edit
    end
  end

  def edit
    @todo = ToDo.find(params[:id])
  end

  def destroy
    ToDo.find(params[:id]).destroy
    redirect_to to_dos_path
  end

  private
  def todos_params
    params.require(:to_do).permit(:list, :description, :completeby)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/to_dos_helper.rb
module ToDosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/to_dos/edit.html.erb
<h1>Editing: <%= @todo.list %></h1>

<%= form_for @todo do |f| %>

<div>
  <%= f.label :list %>
  <%= f.text_field :list, placeholder: 'New Thing ToDo', required: true %>
</div>
<div>
  <%= f.label :description %>
  <%= f.text_field :description, placeholder: 'Description', required: false %>
</div>
<div>
  <%= f.label :completeby %>
  <%= f.date_select :completeby, required: false %>
</div>
  <%= f.submit %>
<% end %>

app/views/to_dos/index.html.erb
<h1>To Do List</h1>

<p><%= link_to 'New Thing To Do', new_to_do_path %></p>

<% @todos.each do |todo| %>
  <div>
    <h2><%= todo.list %> <%= link_to 'Show Notes', to_do_path(todo) %></h2>
    <%= link_to 'Delete', to_do_path(todo), method: :delete %>
  </div>
<% end %>

app/views/to_dos/new.html.erb
<h1>New To Do</h1>

<%= form_for @todo do |f| %>

<div>
  <%= f.label :list %>
  <%= f.text_field :list, placeholder: 'New Thing ToDo', required: true %>
</div>
<div>
  <%= f.label :description %>
  <%= f.text_field :description, placeholder: 'Description', required: false %>
</div>
<div>
  <%= f.label :completeby %>
  <%= f.date_select :completeby, required: false %>
</div>
  <%= f.submit %>
<% end %>

app/views/to_dos/show.html.erb
<h1><%= @todo.list %></h1>
<h4><%= @todo.description %></h4>
<p>Complete by this day: <%= @todo.completeby %></p>
<%= link_to 'Edit', edit_to_do_path(@todo) %>
<%= link_to 'Back', to_dos_path %>